mybatis:
  typeAliasesPackage: com.example.mybdemo.domain
  mapperLocations: classpath*:mapper/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

spring:
  datasource:
    url: jdbc:mysql://hdp2.ambari:3306/api?Unicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: MySQL2.mid
    driver-class-name: com.mysql.jdbc.Driver